apiVersion: v1
kind: Service
metadata:
  name: webstore
spec:
  type: NodePort
  selector:
    app: webstore
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
